// capture-es - bitdrift's ES SDK
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

import NativeBdReactNative from './NativeBdReactNative';
import {
  LogLevels,
  serializeFields,
  type LogLevel,
  type SerializableLogFields,
} from './log';

/** The completion status of a span. */
export enum SpanResult {
  SUCCESS = 'success',
  FAILURE = 'failure',
  CANCELED = 'canceled',
  UNKNOWN = 'unknown',
}

/** A started Capture span. Call {@link end} exactly once when the operation finishes. */
export interface Span {
  /** The UUID generated by Capture for this span. Use it as a child span's parentSpanId. */
  readonly id: string;

  /**
   * Ends this span. Repeated calls have no effect.
   *
   * If startTimeMs was supplied to startSpan, supply endTimeMs here as well. Both values
   * are milliseconds since the Unix epoch.
   */
  end(
    result: SpanResult,
    fields?: SerializableLogFields,
    endTimeMs?: number,
  ): void;
}

class NativeSpan implements Span {
  private hasEnded = false;

  public constructor(public readonly id: string) {}

  public end(
    result: SpanResult,
    fields?: SerializableLogFields,
    endTimeMs?: number,
  ): void {
    if (this.hasEnded) {
      return;
    }

    this.hasEnded = true;
    NativeBdReactNative.endSpan(this.id, result, serializeFields(fields), endTimeMs);
  }
}

/**
 * Starts a Capture span.
 *
 * The native SDK records a span start log immediately and records its corresponding end log
 * when {@link Span.end} is called. Returns null when Capture has not started.
 */
export function startSpan(
  name: string,
  level: LogLevel,
  fields?: SerializableLogFields,
  startTimeMs?: number,
  parentSpanId?: string,
): Span | null {
  const id = NativeBdReactNative.startSpan(
    name,
    LogLevels[level],
    serializeFields(fields),
    startTimeMs,
    parentSpanId,
  );

  return id === null ? null : new NativeSpan(id);
}
