/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Logger {
  constructor(apiKey: string, apiAddress: string, sdkDirectory: string, appId: string, appVersion: string, platform: string, platformVersion: string, locale: string)
  get sessionId(): string
  get deviceId(): string
  log(level: number, message: string, fields: Record<string, string | number | boolean | Buffer>): void
}
