// capture-es - bitdrift's ES SDK
// Copyright Bitdrift, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Logger {
  constructor(apiKey: string, apiAddress: string, sdkDirectory: string, appId: string, appVersion: string, platform: string, platformVersion: string, locale: string)
  get sessionId(): string
  get deviceId(): string
  log(level: number, message: string, fields: Record<string, string | number | boolean | Buffer>): void
}
