name: Update Capture SDK version
on:
    workflow_call:
      inputs:
        version:
          description: 'The Capture SDK version to release, ex: 0.18.6'
          required: true
          type: string
    workflow_dispatch:
      inputs:
        version:
          description: 'The Capture SDK version to release, ex: 0.18.6'
          required: true
          type: string
          
jobs:
  update-rn-capture:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run update_rn_capture_version.sh
        run: ./scripts/update_rn_capture_version.sh ${{ inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update version to ${{ inputs.version }}
          commit-message: Update React Native version with Capture SDK ${{ inputs.version }}
          committer: GitHub Action <noreply@github.com>
          base: main
          delete-branch: true
          branch: update-rn-capture-version-${{ inputs.version }}